import type { Prisma, PrismaClient } from '@prisma/client';
import { SCHEMA_STATEMENTS } from './schema-statements';

/** 新库建表与旧库迁移共用入口；失败时回滚并阻止服务启动。 */
export async function initializeSchema(prisma: PrismaClient): Promise<void> {
  await prisma.$transaction(async (tx) => {
    for (const statement of SCHEMA_STATEMENTS) {
      await tx.$executeRawUnsafe(statement);
    }

    const migrations = await tx.$queryRawUnsafe<Array<{ version: number }>>(
      'SELECT "version" FROM "SchemaMigration"',
    );
    if (!migrations.some((migration) => migration.version === 1)) {
      const adminColumns = await columnNames(tx, 'AdminUser');
      if (!adminColumns.has('sessionVersion')) {
        await tx.$executeRawUnsafe(
          'ALTER TABLE "AdminUser" ADD COLUMN "sessionVersion" INTEGER NOT NULL DEFAULT 0',
        );
      }
      const accountColumns = await columnNames(tx, 'Account');
      if (!accountColumns.has('redeemedByCard')) {
        await tx.$executeRawUnsafe('ALTER TABLE "Account" ADD COLUMN "redeemedByCard" TEXT');
      }
      // 历史数据只能可靠恢复各卡的主账号，不能猜测过去未记录的附加交付。
      await tx.$executeRawUnsafe(
        `UPDATE "Account" SET "redeemedByCard" = "cardKey" WHERE "redeemStatus" = 'redeemed' AND "redeemedByCard" IS NULL`,
      );
      await tx.$executeRawUnsafe('INSERT INTO "SchemaMigration" ("version") VALUES (1)');
    }
    await tx.$executeRawUnsafe('ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "stagedCredential" TEXT');
    await tx.$executeRawUnsafe(
      'ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "refreshHeld" BOOLEAN NOT NULL DEFAULT false',
    );
    await tx.$executeRawUnsafe(
      'CREATE INDEX IF NOT EXISTS "Account_redeemedByCard_idx" ON "Account"("redeemedByCard")',
    );
    await tx.$executeRawUnsafe('ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "stockKind" TEXT NOT NULL DEFAULT \'standard\'');
    await tx.$executeRawUnsafe('ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "teamStatus" TEXT');
    await tx.$executeRawUnsafe('ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "workspaceId" INTEGER');
    await tx.$executeRawUnsafe('ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "kickedAt" TIMESTAMP');
    await tx.$executeRawUnsafe('ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "priorUserId" TEXT');
    await tx.$executeRawUnsafe('ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "priorRemoteWorkspaceId" TEXT');
    await tx.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "Account_stockKind_idx" ON "Account"("stockKind")');
    await tx.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "Account_teamStatus_idx" ON "Account"("teamStatus")');
    await tx.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "Account_workspaceId_idx" ON "Account"("workspaceId")');
    await tx.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "Account_team_active_email_key" ON "Account" (lower("email")) WHERE "stockKind" = \'team\' AND COALESCE("teamStatus", \'\') <> \'kicked\' AND "email" IS NOT NULL');
    await tx.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TeamWorkspace" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "openaiWorkspaceId" TEXT,
      "motherEmail" TEXT NOT NULL,
      "displayName" TEXT,
      "sessionCipher" TEXT NOT NULL,
      "sessionStatus" TEXT NOT NULL DEFAULT 'unknown',
      "lastSuccessAt" TIMESTAMP,
      "lastError" TEXT,
      "socksCipher" TEXT,
      "seatsEntitled" INTEGER,
      "memberCount" INTEGER,
      "snapshotComplete" BOOLEAN NOT NULL DEFAULT false,
      "snapshotAt" TIMESTAMP,
      "willRenew" BOOLEAN,
      "activeUntil" TEXT,
      "lastInviteAt" TIMESTAMP,
      "inviteHold" TEXT,
      "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP NOT NULL
    )`);
    await tx.$executeRawUnsafe('ALTER TABLE "TeamWorkspace" ADD COLUMN IF NOT EXISTS "inviteHold" TEXT');
    await tx.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "TeamWorkspace_openaiWorkspaceId_key" ON "TeamWorkspace"("openaiWorkspaceId")');
    await tx.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "TeamWorkspace_motherEmail_idx" ON "TeamWorkspace"("motherEmail")');
    await tx.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TeamSecret" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "accountId" INTEGER NOT NULL,
      "passwordCipher" TEXT NOT NULL,
      "totpCipher" TEXT NOT NULL,
      "tokenCipher" TEXT,
      "socksCipher" TEXT,
      "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP NOT NULL,
      CONSTRAINT "TeamSecret_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account" ("id") ON DELETE CASCADE ON UPDATE CASCADE
    )`);
    await tx.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "TeamSecret_accountId_key" ON "TeamSecret"("accountId")');
    await tx.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TeamUsage" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "accountId" INTEGER NOT NULL,
      "pct5h" DOUBLE PRECISION,
      "reset5h" INTEGER,
      "pct7d" DOUBLE PRECISION,
      "reset7d" INTEGER,
      "limitReached" BOOLEAN,
      "allowed" BOOLEAN,
      "status" TEXT NOT NULL DEFAULT 'unprobed',
      "detail" TEXT,
      "probedAt" TIMESTAMP,
      CONSTRAINT "TeamUsage_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account" ("id") ON DELETE CASCADE ON UPDATE CASCADE
    )`);
    await tx.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS "TeamUsage_accountId_key" ON "TeamUsage"("accountId")');
    await tx.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TeamJob" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "workspaceRowId" INTEGER NOT NULL,
      "kind" TEXT NOT NULL,
      "status" TEXT NOT NULL DEFAULT 'running',
      "message" TEXT,
      "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updatedAt" TIMESTAMP NOT NULL,
      CONSTRAINT "TeamJob_workspaceRowId_fkey" FOREIGN KEY ("workspaceRowId") REFERENCES "TeamWorkspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE
    )`);
    await tx.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS "TeamJob_workspaceRowId_status_idx" ON "TeamJob"("workspaceRowId", "status")');
  }, { timeout: 30000 });
}

async function columnNames(tx: Prisma.TransactionClient, table: string): Promise<Set<string>> {
  const rows = await tx.$queryRawUnsafe<Array<{ column_name: string }>>(
    `SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = '${table}'`,
  );
  return new Set(rows.map((row) => row.column_name));
}
